# Debug mode may cause many logs
debug: true
# directory to host and store data
data_dir: ./data
# http root
http_root: /iso/
# add discord webhook URL to notify status
#webhook: "https://discord.com/api/webhooks/XXXXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
# Use checksum to check local file sanity check
strict: false
# task execution time (localtime. If in docker, UTC)
run_time: "16:00"
# limit of retrying HTTP request
retry: 5
# limit to save versions per os
limit: 5
